namespace BadgeForge.Core.Data.Validation;

/// <summary>
/// Standard error code constants for pre-flight validation issues.
/// </summary>
public static class PreFlightErrorCodes
{
    public const string MissingRequiredField = "MissingRequiredField";
    public const string MissingPhotoFile = "MissingPhotoFile";
    public const string InvalidBarcode = "InvalidBarcode";
    public const string DuplicateIdentifier = "DuplicateIdentifier";
}

/// <summary>
/// Comprehensive diagnostic report generated by the pre-flight validation engine before batch printing.
/// Acts as the execution gate controlling whether a batch may commence.
/// </summary>
public record PreFlightValidationReport
{
    public int TotalRecords { get; init; }

    public IReadOnlyList<ValidationIssue> Issues { get; init; } = Array.Empty<ValidationIssue>();

    public bool HasErrors => Issues.Any(i => i.Severity == ValidationSeverity.Error);

    public bool HasWarnings => Issues.Any(i => i.Severity == ValidationSeverity.Warning);

    public int ErrorCount => Issues.Count(i => i.Severity == ValidationSeverity.Error);

    public int WarningCount => Issues.Count(i => i.Severity == ValidationSeverity.Warning);

    public IReadOnlyList<ValidationIssue> Errors =>
        Issues.Where(i => i.Severity == ValidationSeverity.Error).ToList();

    public IReadOnlyList<ValidationIssue> Warnings =>
        Issues.Where(i => i.Severity == ValidationSeverity.Warning).ToList();

    public IReadOnlyList<ValidationIssue> MissingFields =>
        Issues.Where(i => i.ErrorCode == PreFlightErrorCodes.MissingRequiredField).ToList();

    public IReadOnlyList<ValidationIssue> MissingPhotos =>
        Issues.Where(i => i.ErrorCode == PreFlightErrorCodes.MissingPhotoFile).ToList();

    public IReadOnlyList<ValidationIssue> InvalidBarcodes =>
        Issues.Where(i => i.ErrorCode == PreFlightErrorCodes.InvalidBarcode).ToList();

    public IReadOnlyList<ValidationIssue> DuplicateIdentifiers =>
        Issues.Where(i => i.ErrorCode == PreFlightErrorCodes.DuplicateIdentifier).ToList();

    /// <summary>
    /// Evaluates the execution gate for starting a print batch.
    /// Critical errors always block and can NEVER be bypassed.
    /// Warnings block by default unless the operator explicitly toggles bypassWarnings to true.
    /// </summary>
    /// <param name="bypassWarnings">Explicit toggle to allow proceeding when only warnings are present.</param>
    /// <returns>True if printing may proceed; false if blocked.</returns>
    public bool CanProceed(bool bypassWarnings = false)
    {
        // Critical errors can never be bypassed
        if (HasErrors)
            return false;

        // Warnings require explicit bypass confirmation
        if (HasWarnings && !bypassWarnings)
            return false;

        return true;
    }

    /// <summary>
    /// Throws an exception if the pre-flight gate blocks batch printing.
    /// </summary>
    public void AssertCanProceed(bool bypassWarnings = false)
    {
        if (HasErrors)
        {
            throw new PreFlightValidationBlockedException(
                $"Pre-flight validation failed with {ErrorCount} critical error(s). Batch printing is blocked and cannot be bypassed.",
                this);
        }

        if (HasWarnings && !bypassWarnings)
        {
            throw new PreFlightValidationBlockedException(
                $"Pre-flight validation completed with {WarningCount} warning(s). Set bypassWarnings to true to proceed.",
                this);
        }
    }
}

/// <summary>
/// Exception thrown when batch printing is attempted against a blocked pre-flight report.
/// </summary>
public class PreFlightValidationBlockedException : InvalidOperationException
{
    public PreFlightValidationReport Report { get; }

    public PreFlightValidationBlockedException(string message, PreFlightValidationReport report)
        : base(message)
    {
        Report = report ?? throw new ArgumentNullException(nameof(report));
    }
}
